name: pp_kits
description: "pp_kits is a rapid development application library for Flutter, containing essential technical points, practical triplet libraries, etc"
version: 1.0.8
homepage: https://github.com/ppswdev/pp_flutter_kits/tree/main/packages/pp_kits

environment:
  sdk: ^3.6.0
  flutter: '>=3.27.0'

dependencies:
  flutter:
    sdk: flutter

  get: ^4.7.2
  intl: ^0.19.0
  path: ^1.9.0
  uuid: ^4.5.1
  archive: ^4.0.7
  audioplayers: ^6.4.0
  connectivity_plus: ^6.1.4
  device_info_plus: ^11.3.0
  file_picker: ^10.1.7
  flutter_easyloading: ^3.0.5
  flutter_screenutil: ^5.9.3
  flutter_secure_storage: ^9.2.4
  flutter_timezone: ^4.1.0
  get_time_ago: ^2.3.1
  image_cropper: ^9.1.0
  image_picker: ^1.1.2
  network_info_plus: ^6.1.4
  package_info_plus: ^8.3.0
  path_provider: ^2.1.5
  share_plus: ^11.0.0
  shared_preferences: ^2.5.3
  url_launcher: ^6.3.1
  open_settings_plus: ^0.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0 

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  uses-material-design: true

  # To add assets to your package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/to/asset-from-package
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/to/font-from-package
