name: pp_kits
description: "pp_kits is a rapid development application library for Flutter, containing essential technical points, practical triplet libraries, etc"
version: 1.0.4
homepage: https://github.com/ppswdev/pp_flutter_kits/tree/main/packages/pp_kits

environment:
  sdk: ">=3.3.0 <4.0.0"
  flutter: ">=3.19.0"

dependencies:
  flutter:
    sdk: flutter

  get: ^4.6.6 #状态管理、依赖管理、路由管理、国际化、主题、中间件等
  intl: ^0.19.0 #国际化
  uuid: ^4.5.0 #UUID生成
  path: ^1.9.0 #文件目录处理库
  timeago: ^3.7.0 #时间格式化
  share_plus: ^10.0.0 #分享
  path_provider: ^2.1.4 #沙盒存储
  audioplayers: ^6.1.0  #音频播放
  url_launcher: ^6.3.0 #打开网页、电话、短信、邮件
  connectivity_plus: ^6.0.5 #网络检测
  #device_info_plus: ^11.1.1 #获取设备信息
  package_info_plus: ^8.0.2 #获取应用信息
  #open_settings_plus: ^0.4.0 #打开系统设置
  shared_preferences: ^2.3.2 #本地轻量数据存储
  flutter_screenutil: ^5.9.3 #屏幕适配
  flutter_secure_storage: ^9.2.2  #本地加密存储
  flutter_easyloading: ^3.0.5 #加载效果，提示框
  archive: ^4.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0 

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  uses-material-design: true

  # To add assets to your package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/to/asset-from-package
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/to/font-from-package
