name: pp_kits
description: "pp_kits is a rapid development application library for Flutter, containing essential technical points, practical triplet libraries, etc"
version: 1.1.0
homepage: https://github.com/ppswdev/pp_flutter_kits/tree/main/packages/pp_kits

environment:
  sdk: ^3.6.0
  flutter: '>=3.27.0'

dependencies:
  flutter:
    sdk: flutter

  dio: ^5.7.0 #网络请求
  get: ^4.7.2 #状态管理
  intl: ^0.19.0 #国际化
  path: ^1.9.0  #文件路径处理
  uuid: ^4.5.1  #生成唯一标识符
  hex: ^0.2.0 #十六进制转换
  encrypt: ^5.0.3 #加密
  archive: ^4.0.7 #压缩和解压缩文件
  audioplayers: ^6.4.0  #audio播放
  connectivity_plus: ^6.1.4 #网络连接状态
  device_info_plus: ^11.3.0 #设备信息
  file_picker: ^10.1.7  #文件选择
  adaptive_dialog: ^2.4.1 #对话框
  flutter_easyloading: ^3.0.5 #加载动画
  flutter_screenutil: ^5.9.3  #屏幕适配
  flutter_secure_storage: ^9.2.4  #安全存储
  flutter_timezone: ^4.1.0  #时区处理
  get_time_ago: ^2.3.1  #时间处理
  image_cropper: ^9.1.0 #图片裁剪
  image_picker: ^1.1.2  #图片选择
  network_info_plus: ^6.1.4 #网络信息
  package_info_plus: ^8.3.0 #应用包信息
  path_provider: ^2.1.5 #文件路径提供
  share_plus: ^11.0.0 #分享功能
  shared_preferences: ^2.5.3  #本地存储
  url_launcher: ^6.3.1  #链接启动
  open_settings_plus: ^0.4.0  #打开系统设置

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0 

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  uses-material-design: true

  # To add assets to your package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/to/asset-from-package
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/to/font-from-package
