/// Localization keys enum
enum PPIntlKey {
  // --- 基础问候 ---
  hello,
  welcome,
  goodbye,
  thankYou,
  sorry,
  helloName,
  welcomeName,

  // --- 通用按钮 ---
  yes,
  no,
  ok,
  confirm,
  cancel,
  done,
  finish,
  back,
  close,
  continueText,
  nextStep,
  skip,
  options,
  refuse,
  submit,
  send,
  reply,
  reset,
  restore,
  details,
  more,
  all,
  preview,
  download,
  upload,
  install,
  backup,
  followSystem,

  // --- 数据操作 ---
  add,
  save,
  edit,
  delete,
  update,
  remove,
  clear,
  search,
  reload,

  // --- 操作结果 ---
  success,
  failed,
  savedSuccessfully,
  deletedSuccessfully,
  addedSuccessfully,
  updatedSuccessfully,

  // --- 应用评分 ---
  appReviewRateTheApp,
  appReviewAppstoreRating,
  appReviewLater,
  appReviewYes,
  appReviewText,
  appReviewText2,

  // --- 协议与隐私 ---
  agreementPrivacyPolicy,
  agreementPrivacyAttr,
  agreementEula,
  agreementEulaAttr,
  agreementSubsciption,
  agreementSubsciptionAttr,
  agreementAgree,
  agreementText,
  agreementUnagreeAlert,

  // --- 确认弹窗 ---
  deleteConfirmTitle,
  deleteConfirmMessage,
  exitConfirmTitle,
  exitPressAgainToExit,
  backToRetry,

  // --- 媒体操作 ---
  pickImage,
  albums,
  fileSource,
  fileSourceDocument,
  cropperImage,
  cameraTakeFailed,

  // --- 复制粘贴 ---
  copyToClipboard,
  copied,
  copiedToClipboard,

  // --- 网络错误 ---
  networkNotAvailable,
  noNetwork,
  networkSettings,
  errorNetworkLost,
  errorRequestTimeout,
  errorRequestTimeoutToRetry,

  // --- 加载状态 ---
  waiting,
  loading,
  processing,

  // --- 下拉刷新 ---
  refreshIdle,
  refreshRefreshing,
  refreshLoading,
  refreshPulling,
  refreshPullup,
  refreshLoadCompleted,
  refreshNoMoreData,

  // --- 空状态 ---
  noData,
  noFavorites,
  noSearchResult,
  invalidValue,
  notYetClear,

  // --- 设置菜单 ---
  settings,
  profile,
  about,
  help,
  favorites,
  share,
  feedback,
  feedbackPlaceHolder,
  language,
  solution,
  contact,
  support,

  // --- 提示与权限 ---
  tipsTitle,
  tipsReminder,
  tipsAttention,
  tipsWarning,
  tipsInfo,
  tipsNote,
  tipsExceptionError,
  tipsRestartOrReinstall,
  tipsUseLimits,
  tipsNetworkText,
  permissionDenied,
  permissionRequired,
  openSettings,

  // --- 版本更新 ---
  upgradeTitle,
  upgradeContent,
  upgradeText,
  upgradeNow,
  upgradeLater,

  // --- 内购相关 ---
  iapPro,
  iapUpgradePro,
  iapPremium,
  iapUpgradePremium,
  iapPurchaseing,
  iapVerifying,
  iapRestoring,
  iapPurchaseFailedTitle,
  iapPurchaseFailedMsg,
  iapRestoreConfirmTitle,
  iapRestoreConfirmMsg,
  iapRestoreSuccessTitle,
  iapRestoreSuccessMsg,
  iapRestoreFailedTitle,
  iapRestoreFailedMsg,
  iapReportTitle,
  iapReportCopied,
  iapReportSend,
  iapFullAccess,
  iapGetAllPermissions,
  iapUnlockAllFeatures,
  iapLimitedTimeGiftTitle,
  iapLimitedTimeGiftText,
  iapLimitedTimeOffer,
  iapLimitedTimeOfferText,
  iapSavedOff,
  iapPurchaseNow,
  iapLifetimeAccess,
  iapShowNormalSubscriptions,
  iapFreeTrialStart,
  iapFreeTrialZero,
  iapFreeTrail,
  iapSubscribe,
  iapFamilyShare,
  iapFamilyShareSetTitle,
  iapFamilyShareSetDesc,
  iapProductAllPlans,
  iapProductSelectPlan,
  iapProductBestValue,
  iapProductWeek,
  iapProductMonth,
  iapProductYear,
  iapWeeklyVip,
  iapMonthlyVip,
  iapYearlyVip,
  iapNoPaymentNow,
  iapCancelAnytime,
  iapProtectByApple,
  iapRestore,
  iapCancelSubscription,
  iapUserPreferred,
  iapBestSubscription,
  iapSubsciptions,
  iapDownloads,
  iapCancelAnytimeWithEase,
  iapTodayFree,
  iapFTI,
  iapFTISubTitle1,
  iapFTISubText1,
  iapFTISubText2,
  iapFTISubText3,
  iapHowCancel,
  iapCancelDesc,
  iapRefund,
  iapWhatDoYouGet,
  iapTBUW,
  iapTBUW1,
  iapTBUW2,
  iapTBUW3,
  iapTBUW4,
  iapTBUW5,
  iapTBUW6,
  iapWP,
  iapSkip,
  iapRemindText,

  // --- 解决方案 ---
  solutionCurrentErrorInfo,
  solutionPurchaseConditions,
  solutionNetworkConnection,
  solutionNetworkConnectionDesc,
  solutionAppStoreAccount,
  solutionAppStoreAccountDesc,
  solutionPaymentMethod,
  solutionPaymentMethodDesc,
  solutionSolutions,
  solutionCheckNetwork,
  solutionCheckNetworkDesc,
  solutionVerifyAppStore,
  solutionVerifyAppStoreDesc,
  solutionCheckPayment,
  solutionCheckPaymentDesc,
  solutionRestartApp,
  solutionRestartAppDesc,
  solutionUpdateSystem,
  solutionUpdateSystemDesc,
  solutionRetry,
  solutionRetryDesc,
  solutionContactSupport,
  solutionContactSupportDesc,

  // --- 设置选项 ---
  settingsThemes,
  settingsSound,
  settingsHapticFeedback,
  settingsLanguage,
  settingsAppicon,
  settingsShare,
  settingsAppreview,
  settingsFeedback,
  settingsRequirementRequest,
  settingsRequirementRequestTip,
  settingsFeedbackTip1,
  settingsFeedbackTip2,
  settingsFeedbackTip3,
  settingsFeedbackTip4,
  settingsFaq,
  settingsAbout,

  // --- 表单相关 ---
  formEmailTitle,
  formEmailEmpty,
  formEmailFormatError,
  formEmailPlaceholder,
  formTitleTitle,
  formTitleEmpty,
  formTitlePlaceholder,
  formFeedbackTitle,
  formFeedbackEmpty,
  formFeedbackPlaceholder,
  formSuggestTitle,
  formSuggestEmpty,
  formSuggestPlaceholder,
  formSubmitSuccess,
  formSubmitFailed,

  // --- 输入规则 ---
  inputRoleNumber,
}
